### PR TITLE
add autoloader / use pregenerated data for location availability map

### PR DESCRIPTION
**Pull request by thrillfall**
This PR provides a (pre-) generating the data needed for displaying the location availability map reducing the load time from ~30s to ~3s.

To generate the data run the wp-cli: `wp map exportLocationAndAvailability`

### CODE REVIEW

**Comment by poilu** [comment]
improvements:
- code convention: snake_case
- individual caching for each map
- store caching data in database, not in file
- use WP cron instead of WP CLI commands
- map settings option to determine caching duration

**Comment by thrillfall** [comment]
done: 
* code convention: snake_case
* individual caching for each map
* store caching data in database, not in file
* use WP cron instead of WP CLI commands

to do
* map settings option to determine caching duration

We need to define the relation between map_id and map_type. If there is only a single map_id per map_type or if there can be more.

**Comment by poilu** [comment]
> We need to define the relation between map_id and map_type. If there is only a single map_id per map_type or if there can be more.

There can exist multiple maps per map type. So the caching data needs to be stored individually (per map_id, if map_type == 1 and option show_item_availability in the map settings is active).

**Comment by poilu** [comment]
> * store caching data in database, not in file

As many other things in Wordpress the maps are posts (with a custom post_type 'cb_map'). That said it would make sense to use native Wordpress mechanisms to store post related data instead of creating separate database tables.
In my eyes post meta data would be suitable: https://developer.wordpress.org/plugins/metadata/managing-post-metadata/

**Comment by thrillfall** [comment]
> > * store caching data in database, not in file
> 
> As many other things in Wordpress the maps are posts (with a custom post_type 'cb_map'). That said it would make sense to use native Wordpress mechanisms to store post related data instead of creating separate database tables. In my eyes post meta data would be suitable: https://developer.wordpress.org/plugins/metadata/managing-post-metadata/

What wp native mechanism are we talking?
How do they improve the way we store and retrieve the cached data?

**Comment by thrillfall** [comment]
> > We need to define the relation between map_id and map_type. If there is only a single map_id per map_type or if there can be more.
> 
> There can exist multiple maps per map type. So the caching data needs to be stored individually (per map_id, if map_type == 1 and option show_item_availability in the map settings is active).

fixed

**Comment by thrillfall** [comment]
Now we are only missing to add a setting for the user to set interval. That we can do. But i don't know how to create and add a custom cron schedule. Do you @poilu ?

**Comment by poilu** [comment]
> Now we are only missing to add a setting for the user to set interval. That we can do. But i don't know how to create and add a custom cron schedule. Do you @poilu ?

I guess it's sufficient to have this option in the plugin settings. So we don't need an individual interval for each map.
This assumed it's the almost the same like on plugin activation. When the settings are saved a new event (always with the  same name) is scheduled. The only difference is that the previously scheduled event hook has to be cleared before with `wp_clear_scheduled_hook($event_name)`, which should be done on plugin deactivation as well.

**Comment by poilu** [comment]
In my eyes we don't need `ExportLocationAndAvailability->write_location_and_availability_for_export_to_cache($map_id)` currently, because availability is not exported and the export is only done once a day anyway.

**Comment by thrillfall** [comment]
> > Now we are only missing to add a setting for the user to set interval. That we can do. But i don't know how to create and add a custom cron schedule. Do you @poilu ?
> 
> I guess it's sufficient to have this option in the plugin settings. So we don't need an individual interval for each map. This assumed it's the almost the same like on plugin activation. When the settings are saved a new event (always with the same name) is scheduled. The only difference is that the previously scheduled event hook has to be cleared before with `wp_clear_scheduled_hook($event_name)`, which should be done on plugin deactivation as well.

Yes yes. But how to create a custom cron schedule? The function you pass to add a New schedule can not be parameterized

**Pull request merged**
